name: Deploy Turborepo to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: 15.206.185.33
          username: ubuntu
          key: ${{ secrets.PRIVATE_SECRET_KEY }}
          port: 22
          script: |
            if[ -d practicingCICD ]; then
              cd practicingCICD 
            else 
              git clone https://github.com/Ashishlakhimale23/practicingCICD.git
              cd practicingCICD
            fi
            git fetch origin main
            git checkout main
            git pull origin main
            npm i  # Clean install for consistency
            npm run build  # Build all Turborepo packages
            cd ..
            cd pm2config
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
            exit 0