name: Deploy Turborepo to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: 65.0.122.42
          username: ubuntu
          key: ${{ secrets.PRIVATE_SECRET_KEY }}
          port: 22
          debug: true  # Enable debug logs
          script: |
            set -e  # Exit on any error
            echo "Starting deployment..."
            cd /home/ubuntu
            if [ -d "/home/ubuntu/practicingCICD" ]; then
              echo "Directory exists, updating..."
              cd /home/ubuntu/practicingCICD
            else
              echo "Cloning repo..."
              git clone https://github.com/Ashishlakhimale23/practicingCICD.git /home/ubuntu/practicingCICD
              cd /home/ubuntu/practicingCICD
            fi
            echo "Fetching and pulling main branch..."
            git fetch origin main
            git checkout main
            git pull origin main
            echo "Installing dependencies..."
            rm -rf node_modules package-lock.json
            npm i  # Cleaner install
            echo "Building Turborepo..."
            npm run build  # Explicit Turborepo build
            echo "Deploying with PM2..."
            if [ -d "/home/ubuntu/pm2config" ]; then
              cd /home/ubuntu/pm2config
              pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
              pm2 save
            else
              echo "Error: /home/ubuntu/pm2config not found"
              exit 1
            fi
            echo "Deployment complete"
            exit 0